options:
  lang: zh_CN
  debug: true
# priority越小，优先级越高
attributes:
  attack:
    name: attack
    priority: 0
    labels: [ 攻击力 ]
    message:
      enable: true
      format: "造成了{0}点伤害"
  armor:
    name: armor
    priority: 0
    labels: [ 护甲 ]
  crit:
    name: crit
    priority: 0
    labels: [ 暴击 ]
  dodge:
    name: dodge
    priority: 1
    labels: [ 闪避几率 ]
